In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("Preprocessed_Heart_data.csv")

In [3]:
dataset

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Sex,ChestPainType,RestingECG,ExerciseAngina,ST_Slope
0,40.0,140.0,289.0,0.0,172.0,0.0,0.0,M,ATA,Normal,N,Up
1,49.0,160.0,180.0,0.0,156.0,1.0,1.0,F,NAP,Normal,N,Flat
2,37.0,130.0,283.0,0.0,98.0,0.0,0.0,M,ATA,ST,N,Up
3,48.0,138.0,214.0,0.0,108.0,1.5,1.0,F,ASY,Normal,Y,Flat
4,54.0,150.0,195.0,0.0,122.0,0.0,0.0,M,NAP,Normal,N,Up
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45.0,110.0,264.0,0.0,132.0,1.2,1.0,M,TA,Normal,N,Flat
914,68.0,144.0,193.0,1.0,141.0,3.4,1.0,M,ASY,Normal,N,Flat
915,57.0,130.0,131.0,0.0,115.0,1.2,1.0,M,ASY,Normal,Y,Flat
916,57.0,130.0,236.0,0.0,174.0,0.0,1.0,F,ATA,LVH,N,Flat
917,38.0,138.0,175.0,0.0,173.0,0.0,0.0,M,NAP,Normal,N,Up

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
dataset

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
0,40.0,140.0,289.0,0.0,172.0,0.0,0.0,1,1,0,0,1,0,0,0,1
1,49.0,160.0,180.0,0.0,156.0,1.0,1.0,0,0,1,0,1,0,0,1,0
2,37.0,130.0,283.0,0.0,98.0,0.0,0.0,1,1,0,0,0,1,0,0,1
3,48.0,138.0,214.0,0.0,108.0,1.5,1.0,0,0,0,0,1,0,1,1,0
4,54.0,150.0,195.0,0.0,122.0,0.0,0.0,1,0,1,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45.0,110.0,264.0,0.0,132.0,1.2,1.0,1,0,0,1,1,0,0,1,0
914,68.0,144.0,193.0,1.0,141.0,3.4,1.0,1,0,0,0,1,0,0,1,0
915,57.0,130.0,131.0,0.0,115.0,1.2,1.0,1,0,0,0,1,0,1,1,0
916,57.0,130.0,236.0,0.0,174.0,0.0,1.0,0,1,0,0,0,0,0,1,0
917,38.0,138.0,175.0,0.0,173.0,0.0,0.0,1,0,1,0,1,0,0,0,1

In [6]:
#dataset=dataset.drop("HeartDisease",axis=1)
dataset

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
0,40.0,140.0,289.0,0.0,172.0,0.0,0.0,1,1,0,0,1,0,0,0,1
1,49.0,160.0,180.0,0.0,156.0,1.0,1.0,0,0,1,0,1,0,0,1,0
2,37.0,130.0,283.0,0.0,98.0,0.0,0.0,1,1,0,0,0,1,0,0,1
3,48.0,138.0,214.0,0.0,108.0,1.5,1.0,0,0,0,0,1,0,1,1,0
4,54.0,150.0,195.0,0.0,122.0,0.0,0.0,1,0,1,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45.0,110.0,264.0,0.0,132.0,1.2,1.0,1,0,0,1,1,0,0,1,0
914,68.0,144.0,193.0,1.0,141.0,3.4,1.0,1,0,0,0,1,0,0,1,0
915,57.0,130.0,131.0,0.0,115.0,1.2,1.0,1,0,0,0,1,0,1,1,0
916,57.0,130.0,236.0,0.0,174.0,0.0,1.0,0,1,0,0,0,0,0,1,0
917,38.0,138.0,175.0,0.0,173.0,0.0,0.0,1,0,1,0,1,0,0,0,1

In [7]:
dataset["HeartDisease"].value_counts()

HeartDisease
1.0    508
0.0    410
Name: count, dtype: int64

In [8]:
indep=dataset[["Age","Sex_M","RestingBP"]]
dep=dataset["HeartDisease"]

In [9]:
indep.shape

(918, 3)

In [10]:
dep

0      0.0
1      1.0
2      0.0
3      1.0
4      0.0
      ...
913    1.0
914    1.0
915    1.0
916    1.0
917    0.0
Name: HeartDisease, Length: 918, dtype: float64

In [11]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [12]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)              
print(clf_report)
print(cm)

              precision    recall  f1-score   support

         0.0       0.59      0.48      0.53       128
         1.0       0.67      0.76      0.71       178

    accuracy                           0.64       306
   macro avg       0.63      0.62      0.62       306
weighted avg       0.63      0.64      0.63       306

[[ 61  67]
 [ 43 135]]

In [13]:
from sklearn.naive_bayes import BernoulliNB
classifier = BernoulliNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)              
print(clf_report)
print(cm)

              precision    recall  f1-score   support

         0.0       0.83      0.41      0.54       128
         1.0       0.69      0.94      0.79       178

    accuracy                           0.72       306
   macro avg       0.76      0.67      0.67       306
weighted avg       0.75      0.72      0.69       306

[[ 52  76]
 [ 11 167]]

In [14]:
from sklearn.naive_bayes import CategoricalNB
classifier =CategoricalNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)              
print(clf_report)
print(cm)

              precision    recall  f1-score   support

         0.0       0.59      0.62      0.60       128
         1.0       0.71      0.69      0.70       178

    accuracy                           0.66       306
   macro avg       0.65      0.65      0.65       306
weighted avg       0.66      0.66      0.66       306

[[ 79  49]
 [ 56 122]]

In [15]:
from sklearn.naive_bayes import ComplementNB
classifier =ComplementNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)              
print(clf_report)
print(cm)

              precision    recall  f1-score   support

         0.0       0.55      0.62      0.59       128
         1.0       0.70      0.63      0.67       178

    accuracy                           0.63       306
   macro avg       0.63      0.63      0.63       306
weighted avg       0.64      0.63      0.63       306

[[ 80  48]
 [ 65 113]]